version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-west-2"
    IMAGE_REPO_NAME: "rkntest1"
    IMAGE_TAG: "latest"
phases:
  install:
    commands:
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
  pre_build:
    commands:
      - echo Logging in to Amazon ECR…
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - mvn clean install
      - echo Building the Docker image…
      - . /root/ev.sh
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"docker-demo","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json
  post_build:
    commands:
      - . /root/ev.sh
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
    files:
      - target/Spring-Boot-Hello-App-0.0.1-SNAPSHOT.war
      - imagedefinitions.json
      - kubeconfig.demoeks-cluster.yaml
