version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-west-2"
    IMAGE_REPO_NAME: "rkntest1"
    IMAGE_TAG: "latest"
phases:
  install:
    commands:
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
  pre_build:
    commands:
      - echo Logging in to Amazon ECR…
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building the Docker image…
      - . /root/ev.sh
      - echo $REPO_URI
      - echo $AWS_ACCOUNT_ID
  post_build:
    commands:
      - echo post_build stage…
      - echo $REPO_URI
      - echo $AWS_ACCOUNT_ID
      - . /root/ev.sh
artifacts:
    files:
      - target/Spring-Boot-Hello-App-0.0.1-SNAPSHOT.war
      - imagedefinitions.json
      - kubeconfig.demoeks-cluster.yaml
