apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNE1UQXlOREV3$
    server: https://892F1A58893A3625175FC18954787544.yl4.us-west-2.eks.amazonaws.com
  name: demoeks-cluster.us-west-2.eksctl.io
contexts:
- context:
    cluster: demoeks-cluster.us-west-2.eksctl.io
    user: iam-root-account@demoeks-cluster.us-west-2.eksctl.io
  name: iam-root-account@demoeks-cluster.us-west-2.eksctl.io
current-context: iam-root-account@demoeks-cluster.us-west-2.eksctl.io
kind: Config
preferences: {}
users:
- name: iam-root-account@demoeks-cluster.us-west-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - demoeks-cluster
      command: aws-iam-authenticator
      env: null
